var annotated_dup =
[
    [ "AnalysisCounter", "class_analysis_counter.html", "class_analysis_counter" ],
    [ "AnalysisRecord", "struct_analysis_record.html", "struct_analysis_record" ],
    [ "Calculator", "class_calculator.html", "class_calculator" ],
    [ "CalculatorComplex", "class_calculator_complex.html", "class_calculator_complex" ],
    [ "CalculatorExpression", "class_calculator_expression.html", "class_calculator_expression" ],
    [ "CalculatorMatrix", "class_calculator_matrix.html", "class_calculator_matrix" ],
    [ "ComplexInfo", "class_complex_info.html", "class_complex_info" ],
    [ "ComplexityCalculator", "class_complexity_calculator.html", "class_complexity_calculator" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "ExpressionAnalyzer", "class_expression_analyzer.html", "class_expression_analyzer" ],
    [ "ExpressionHistory", "class_expression_history.html", "class_expression_history" ],
    [ "ExpressionStats", "struct_expression_stats.html", "struct_expression_stats" ],
    [ "History", "class_history.html", "class_history" ],
    [ "HistoryMemory", "class_history_memory.html", "class_history_memory" ],
    [ "Matrix", "class_matrix.html", "class_matrix" ],
    [ "Memory", "class_memory.html", "class_memory" ],
    [ "MemoryCell", "struct_memory_cell.html", "struct_memory_cell" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "MenuInput", "class_menu_input.html", "class_menu_input" ],
    [ "MenuOutput", "class_menu_output.html", "class_menu_output" ],
    [ "Record", "struct_record.html", "struct_record" ],
    [ "RecordHistory", "struct_record_history.html", "struct_record_history" ],
    [ "Testing", "class_testing.html", "class_testing" ]
];